### PR TITLE
Update dynatrace-oneagent-operator to 0.9.0

### PR DESCRIPTION
**Pull request by DTMad**
New version for the Dynatrace-OneAgent-Operator

### CODE REVIEW

**Comment by DTMad** [comment]
Ping @PennyScissors

**Comment by pennyscissors** [comment]
@DTMad Could you please separate this PR into 2 commits as following to make it easier to review? Thanks in advance.
1st commit: Copy the previous chart into a new folder v0.9.0.
2nd commit: Make the changes to update the chart to v0.9.0.

Also, can I close [this other PR](https://github.com/rancher/helm3-charts/pull/28) as it is an older version of the chart? Users always get the latest version as default when installing, so updating older versions once a new version is available is not needed. Unless there is a specific use case where installing an older version of your chart is preferable.

**Comment by DTMad** [comment]
Hey @PennyScissors,
since our PRs for version 0.8.2 and 0.9.0 haven't been merged yet I could base it on them.

**Comment by pennyscissors** [comment]
That's okay, you could also rebase the other PR and I'll review it first. What I wanted to point out is that you could skip 0.8.2 because current users can update to 0.9.0 and skip 0.8.2, and new users will see the latest (0.9.0) as default for installation in the UI.

**Comment by DTMad** [comment]
OK, sounds good!
I'm totally fine with not having 0.8.2 and 0.9.0 but only the latest (0.9.2).
I will rebase the corresponding PR and close the ones for the older versions.

**Comment by pennyscissors** [comment]
@DTMad Perfect, you can submit a PR for 0.9.2 and close the others. I'll make sure to review it before the end of this week.

**Comment by DTMad** [comment]
Closed since version 0.9.2 is available - see https://github.com/rancher/helm3-charts/pull/46

**Pull request closed without merging**
