### PR TITLE
Add helm3 chart for StorageOS v2.1.0

### PR DESCRIPTION
**Pull request by darkowlzz**
This adds StorageOS chart in rancher helm3 chart catalog. This is based on the previous chart in https://github.com/rancher/charts/tree/master/proposed/storageos-operator, updated to support helm3.

### CODE REVIEW

**Comment by croomes** [comment]
This has been tested by StorageOS and we think it's ready for merging, but please let us know if you have questions.

There is an equivalent update for Helm 2: https://github.com/rancher/charts/pull/482

**Comment by deniseschannon** [comment]
@croomes Are there any changes that require Helm3 support? Would Helm2 chart be sufficient?

**Comment by croomes** [comment]
Hi @deniseschannon, we've also updated our original Helm 2 chart for the same version of Storageos (v2.1.0), but due to the install_crd being removed in Helm 3 it's not compatible.  We opted to add Helm 3 so that users would have a choice, but I expect most will stick with the default until Rancher moves to Helm 3, although we've had quite a few requests for Helm 3 support.  Does that fit in with Marketplace plans?

**Comment by darkowlzz** [comment]
Helm2 chart has been update and that should be enough for now. Closing this.

**Pull request closed without merging**
