### PR TITLE
Created Lightstep satellite chart

### PR DESCRIPTION
**Pull request by AjohnsonLS**

### CODE REVIEW

**Comment by pennyscissors** [comment]
@AjohnsonLS Looks like the chart files are missing.

**Comment by AjohnsonLS** [comment]
a .git folder snuck in there. Thanks

**Comment by pennyscissors** [comment]
There are some files and directories in your chart that shouldn't be there (git/github stuff, and a extra charts directory, etc). Please use the following as reference for the chart's file structure. 

Docs on file structure
https://github.com/rancher/helm3-charts#rancher-chart-structure

Chart for reference
https://github.com/rancher/helm3-charts/tree/master/charts/dynatrace-oneagent-operator

**Comment by pennyscissors** [comment]
@AjohnsonLS Just noticed we lost track of this PR. Is this update still relevant or would you prefer to submit a new PR?

**Comment by pennyscissors** [comment]
Closing as there hasn't been any activity for a while.

**Pull request closed without merging**
