### PR TITLE
Add dynatrace-oneagent-operator v0.8.0

### PR DESCRIPTION
**Pull request by DTMad**

### CODE REVIEW

**Comment by DTMad** [comment]
Linting failed because of a down time of GitHub (server error 500) - should be fine once you retrigger ;)

**Comment by DTMad** [comment]
Hey @guangbochen!
Do you have time to have a quick look at this please? Thx :)

**Comment by pennyscissors** [comment]
@DTMad I'll go ahead and review this for you. 
First, could you please separate this into two commits to make it easier to review?
1st commit: Copy the older version of the chart into a new folder named after the new version.
2nd commit: Changes made to the older version to update it.

**Comment by DTMad** [comment]
Hey @PennyScissors !

Sure!
Updated this PR so it is the older version in the new folder.
Created a 2nd PR (which I will rebase when this one is reviewed and merged) with the actual changes:
https://github.com/rancher/helm3-charts/pull/20

Thanks

**Comment by DTMad** [comment]
Provided changes in new PR: https://github.com/rancher/helm3-charts/pull/20 -> Closed

**Pull request closed without merging**
