### PR TITLE
Update nginx-ingress to v0.8.0

### PR DESCRIPTION
**Pull request by Dean-Coakley**
* Update to latest NGINX Ingress Controller release: https://github.com/nginxinc/kubernetes-ingress/releases/tag/v1.10.0

### CODE REVIEW

**Review by pennyscissors — COMMENTED** [review]
Hello @Dean-Coakley, could you please redo this PR to have 2 commits as following so that it's easier to review?

1st commit: Make a copy of the previous version of the chart into a new folder.
2nd commit: Apply the changes made to the older version to update it.

Example [PR](https://github.com/rancher/helm3-charts/pull/33) for reference.

**Comment by Dean-Coakley** [comment]
Hi @PennyScissors, 

I was trying to follow that structure before. I'm still unsure if/what I did incorrectly. 
However, I found a lot of changes in the latest commit that were not required. I removed those, hopefully that is helpful anyway. 

Note that most of the changes came from a dependency update that made all CRDs have a different indentation level. 

Let me know if there is anything I can do to help.

**Comment by pennyscissors** [comment]
Thanks @Dean-Coakley, as long as the second commit has the changes you would expect the newest version of the chart to have, then it's all good.

**Comment by pennyscissors** [comment]
I'm running into the following problem during installation in Rancher v2.5.6 with default chart values. I installed the previous nginx-ingress version v.0.7.1 using default values as well and it installed successfully, but it will fail the upgrade for the same reason. Could you please test this in Rancher, or provide the steps install it if this is user error from my part?

```
Failed to install app nginx-ingress. 
Error: error while running post render on files: error while running command /kustomize.sh. error output: 2021/03/09 21:58:36 got file 'all.yaml', but '/all.yaml' must be a directory to be a root 
Error: accumulating resources: accumulating resources from 'all.yaml': may not add resource with an already registered id: networking.k8s.io_v1beta1_IngressClass|~X|nginx : exit status 1
```

**Comment by Dean-Coakley** [comment]
@PennyScissors My bad. Should be fixed now.
(There was a duplicate template trying to install the IngressClass resource)

**Review by pennyscissors — APPROVED** [review]

**Pull request merged**
