### PR TITLE
Openebs Helm3 changes and openebs version update

### PR DESCRIPTION
**Pull request by nareshdesh**
Helm3 related command changes and updated openebs to latest version

### CODE REVIEW

**Comment by nareshdesh** [comment]
@PennyScissors , can you please help in getting CI passed

**Comment by pennyscissors** [comment]
Hello @nareshdesh, Our CI is broken at the moment. We are working on improving the whole pipeline, but it's not ready yet. Could you please use Helm's chart-testing tool directly from [here](https://github.com/helm/chart-testing), and run ct lint against our repo? Thanks

**Comment by nareshdesh** [comment]
@PennyScissors , ran the `ct lint` and following is the output
```/helm3-charts/charts/openebs # git status
On branch rel-250
Your branch is up to date with 'origin/rel-250'.

nothing to commit, working tree clean
/helm3-charts/charts/openebs # ct lint
Linting charts...
------------------------------------------------------------------------------------------------------------------------
No chart changes detected.
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
/helm3-charts/charts/openebs # git remote -v
origin  https://github.com/nareshdesh/helm3-charts.git (fetch)
origin  https://github.com/nareshdesh/helm3-charts.git (push)
```
Can you approve it ,if all looks good

**Comment by nareshdesh** [comment]
@PennyScissors , can we move forward with the merge. 
Let me know, if anything is blocking

**Comment by PennyScissors** [comment]
Hello @nareshdesh, the output you provided shows that no charts were linted. However, I linted it for you and it's all good.

Output:

For future reference you can lint the chart by doing the following:
1. Add the rancher remote to your fork and fetch master
```
git remote add rancher-helm3-charts https://github.com/rancher/helm3-charts.git
```

**Comment by pennyscissors** [comment]
Hello @nareshdesh, the output you provided shows that no charts were linted. However, I linted it for you and it's all good.

For future reference you can lint helm3 charts by doing the following:

1. Add the rancher remote to your fork and fetch master as following
```
git remote add -ft master rancher-helm3-charts https://github.com/rancher/helm3-charts.git
```
2. Run ct lint:
```
docker run -v $(pwd):/rancher-helm3-charts -w /rancher-helm3-charts quay.io/helmpack/chart-testing:latest ct lint \
--remote rancher-helm3-charts \
--target-branch master \
--validate-maintainers=false \
--chart-dirs charts/openebs
```

The output should look like this:
```
---------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")
------------------------------------------------------------------------------------------------------------------------

Linting chart 'openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")'
Checking chart 'openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")' for a version bump...
Unable to find chart on master. New chart detected.
Validating /rancher-helm3-charts/charts/openebs/v2.5.0/Chart.yaml...
Validation success! 👍
==> Linting charts/openebs/v2.5.0

1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✔︎ openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")
--------------------------------------------------------------------------------------
```

**Review by pennyscissors — CHANGES_REQUESTED** [review]
There are other openebs charts in [rancher/charts](https://github.com/rancher/charts/tree/master/charts/openebs) (helm 2 charts). If your intention is to migrate the new openebs chart to this repo (helm 3 charts), be aware that you will need to maintain the chart in both repos so our catalogs won't show two different versions of openebs as the latest available, or set a constraint in `question.yaml` so that only one of the charts show up from a specific Rancher version onwards. If this was not intentional, please close this PR and open a new one updating the chart in [rancher/charts](https://github.com/rancher/charts/). [Example PR](https://github.com/rancher/charts/pull/777) of a previous openebs chart update for reference.

**Comment by nareshdesh** [comment]
@PennyScissors ,  We would like to continue with helm3 charts from the rancher version ( 2.4? ) which supports helm3. 

Could not understand what you meant by the following 
```be aware that you will need to maintain the chart in both repos so our catalogs won't show two different versions of openebs as the latest available, or set a constraint in question.yaml``` 
Do you mean,  we also need to update the helm2 chart with the latest version of Openebs version

Our objective is to use helm3 charts from the version of rancher supporting helm3 and for the older version of rancher, which does not supports helm3, we would like the end users to be able to use the helm2 charts.
Can you guide me on how to achieve this.

**Comment by pennyscissors** [comment]
@nareshdesh
In the Cluster Manager UI (default UI in Rancher v2.4) users have access to the `library` catalog which are Helm 2 charts from the `rancher/charts` repository, and `helm3-library` has Helm 3 charts from the `rancher/helm3-charts` repository. You currently have charts in both repositories. What I meant by my last comment is that you would need to maintain the chart in both repositories if you want to keep them both up to date since they are technically different charts.

An important detail is that Rancher v2.3 has reached end of maintenance/life, and since Helm 3 is supported in Rancher v2.4+, there is no need to use rancher/charts anymore unless you want to specifically continue supporting your Helm 2 chart for users that haven't updated to Rancher v2.4+.

My suggestion was to set a constraint (E.g. Rancher v2.5.6) for the charts in the rancher/charts repository so that they are hidden for Rancher v2.5.6+ installations and basically deprecate them without affecting users with existing installations, and you could then focus on your Helm 3 chart in rancher/helm3-charts from this point onwards.

**Comment by nareshdesh** [comment]
@PennyScissors ,  I have raised PR for helm2 charts and have set the rancher_max_version in it to 2.5.6 for now. 
We will continue to update both the charts until 2.5.6 reaches end of maintenance/life and there after we will maintain helm3 charts only.
Can you please take a look at both the PR and approve it, if all looks good

Following is the PR for helm2 chart: https://github.com/rancher/charts/pull/1034

**Comment by nareshdesh** [comment]
@PennyScissors , can you please review this PR and approve it, if all looks good

**Review by pennyscissors — APPROVED** [review]

**Comment by nareshdesh** [comment]
@PennyScissors , Do we also need to push the changes to partner-charts (https://github.com/rancher/partner-charts)
On Rancher dashboard `dashboard/c/local/apps/charts` (it can be reached through cluster explorer),  the openEBS version being listed is very old.

**Pull request merged**
